### ISSUE TITLE
Can the license be changed to MIT?

### ISSUE THREAD

**Issue by koder217** [Open3270/Open3270#28]
Was wondering if license for this project be changed to MIT or Apache2.0. LGPL is complicated and restrictive.

**Comment by igitur** [comment]
@MikeWarriner wrote most of the code. I will go with his decision.

**Comment by koder217** [comment]
Thanks for the quick reply @igitur !

**Comment by MikeWarriner** [comment]
I'm relaxed about this. Best to let me know which you'd prefer and unless @igitur has any concerns I'm happy to change the license.

**Comment by koder217** [comment]
MIT !!!

Thanks @MikeWarriner

**Comment by igitur** [comment]
Thanks @MikeWarriner . Do you know of any other contributors who should give their permission?

**Comment by MikeWarriner** [comment]
I think we're good.  I've updated the license to MIT in the LICENSE.TXT and all C# files.  Enjoy the freedom.

**Comment by koder217** [comment]
I can't thank you enough @MikeWarriner and @igitur  !!

**Comment by igitur** [comment]
Please help by contributing back. And I now there are a few PRs in the queue already.

**Comment by koder217** [comment]
Sure @igitur I have few improvements which will be in a PR soon.
