### ISSUE TITLE
Becoming A Contributor

### ISSUE THREAD

**Issue by mipoleon** [Open3270/Open3270#32]
Can I be added as a contributor?  I got some fixes I would like to submit back to the project.

**Comment by igitur** [comment]
You are now a contributor.

**Comment by mipoleon** [comment]
Are you being sarcastic?

**Comment by igitur** [comment]
Yup.

This is open source software. If you want to contribute, then contribute. You don't need permission or approval.

**Comment by mipoleon** [comment]
Then why do I get this error when trying to push my updates? "remote:
Permission to Open3270/Open3270.git denied to mipoleon. unable to access '
https://github.com/Open3270/Open3270.git/': The requested URL returned
error: 403"

**Comment by igitur** [comment]
Please submit your contributions through pull requests.

**Comment by bencz** [comment]
Fork the project
Add your changes to your fork
push the changes to your fork
create a pull-request

**Comment by mipoleon** [comment]
Thank you.  I believe I have completed those steps so there should be a
request out there for you.  This is my 1st time syncing to Github like this
so hopefully everything is in order.
