### ISSUE TITLE
One branch to rule them all!

### ISSUE THREAD

**Issue by cbuosi** [Open3270/Open3270#4]
Merge/combine (or delete) chris_hulbert + clyde_coulter + codeplex_forums in just one...

Is there a reason to have 3 branches? Besides that old 0000040000032 (or something like that) error?

**Comment by igitur** [comment]
The branches were already merged if I remember correctly. They still remain as a remnant after the import to Github.

**Comment by cbuosi** [comment]
@igitur  nice! Thanks!
